### ISSUE TITLE
Spyder fails to launch above version 3.3.2 when control module is installed.

### ISSUE THREAD

**Issue by hjcmeche2017** [python-control/python-control#290]
I have tried running the most updated version of spyder at the time (3.3.3) and doing so prevents spyder from being launched (in base root environment). I tried creating a separate environment, but I have to stick to the older version (3.3.2) for it to work otherwise it will crash spyder.

**Comment by repagh** [comment]
Is this specific to python-control, i.e., do the crashes occur with import of python-control? Or due to having python-control installed, and related changes in your python environment?

If it is only spyder-related, you should report somewhere else. 

In any case, your message contains insufficient information. What OS are you running, OSX, WIndows or Linux? How did you install spyder and python? With conda or pip, or otherwise? Which version of python are you running? Which version of python-control?

I am closing this. Feel free to re-open if this is specifically about python-control, and then give some more specific information on the bug.
