### ISSUE TITLE
StateSpace gain difference vs Matlab/Scipy

### ISSUE THREAD

**Issue by db87** [python-control/python-control#368]
It seems that the Control toolbox StateSpace class is generating the incorrect DC gain value in this case.  Matlab agrees with Scipy, both of which give me the correct physical result for my model too.

A simplified version of the issue I am having is:
```
import control
import scipy.signal

A,B,C,D = (-0.66848564, 1, 2.19236215, 6.613174062386491)

ss = control.StateSpace(A,B,C,D)
print(ss.zero(), ss.dcgain())
print('control version', control.__version__)

ss = scipy.signal.StateSpace(A,B,C,D)
zpk = ss.to_zpk()
print(zpk.zeros, zpk.gain)
print('scipy version', scipy.__version__)

> [-1.+0.j] 9.892769043663876
> control version 0.8.2
> [-1.] 6.613174062386491
> scipy version 1.3.2
```

**Comment by murrayrm** [comment]
The problem is  not with `dcgain`, but rather that you are comparing two different things.  When you call `ss.to_zpk()` you get a system of the form
```
  6.61 (s+1)
  ----------
  (s+0.668)
```
The "gain" of this system in a ZPK representation is 6.61, but the "DC gain" of the system is the value of the transfer function at s = 0, which is 6.61 * 1 / 0.668 = 9.89.

In MATLAB, try `dcgain(ss)` and you should get the same thing as python-control.
