### ISSUE TITLE
Fix for bug in margin.py

### ISSUE THREAD

**Issue by callawaycass** [python-control/python-control#58]
Calling margin() or stability_margins() with (mag, phase, omega) form yields incorrect result. I found that the issue is in line 125 of margin.py, where it calls frdata.FRD to create the system:

    sys = frdata.FRD(mag*np.exp((1j/360.)*phase), omega, smooth=True)

The phase angle conversion is incorrect. Changing this line to:

    sys = frdata.FRD(mag*np.exp(1j*phase*np.pi/180), omega, smooth=True)

yields the correct result. Also, it may be good to clearly indicate that the magnitude data in this form must be absolute magnitude, not dB, and that the phase must be in degrees. The frequency can be either Hz or rad/s... the output frequency is in the same units as whatever you put in (Matlab's documentation has a similar note).

**Comment by cwrowley** [comment]
Good catch--thanks @callawaycass

Now that you pointed this out, it seems inconsistent for this routine to take phase inputs in degrees, while `sys.freqresp(omega)` returns phases in radians.  For instance, one might expect the following code to work:
```
sys = TransferFunction(1,[1,1])
mag, phase, omega = sys.freqresp(np.logspace(-1,1,100))
margins = stability_margins((mag,phase,omega))
```
but the units of phase are wrong.  So I wonder if we should change `freqresp` to return phase in degrees, in order to be more consistent?  I notice the docstring for `freqresp` doesn't specify the units of phase either, so regardless of whether we change the routine, we should improve the documentation.
