### ISSUE TITLE
Nyquist plot with imaginary poles, semi-circles only working after 'trick'

### ISSUE THREAD

**Issue by kevindekemele** [python-control/python-control#613]
I'm plotting the Nyquist diagram of a transfer function which has poles on the imaginary axis:

```

import control
import matplotlib.pyplot as plt
import numpy as np

K = 1

Gp =  control.tf([1], [1,1,0,0,0]) 
Gc = control.tf([K], [1]) 


control.nyquist_plot(Gp*Gc,plot=True,omega_num=1000)
plt.show()

```
Which results in the following incorrect plot, that does not show infinte semicircles, but something incorrect:
![image](https://user-images.githubusercontent.com/11015732/115715659-a683f180-a378-11eb-9f3f-99efe15967f4.png)

Also using `indent_direction` and `indent_radius` did not solve this.
The trick I found that makes it work is if I add `omega_limits=[0.001,10000]` to nyquist_plot:

![image](https://user-images.githubusercontent.com/11015732/115715678-ab48a580-a378-11eb-96fc-5eac7222df88.png)

Can you please fix such that the incorrect 'line' does not appear?

**Comment by bnavigator** [comment]
Yes, the algorithm to determine the default omega vector for the system starts with a lower frequency of 0.1, because the pole of the system is at -1.

https://github.com/python-control/python-control/blob/e81f648431e2a9f2cdf583702522bc2af0e1c360/control/freqplot.py#L1088-L1092

The "trick" to manually define the omega limits is the correct way to override the default omega vector determination.

**Comment by kevindekemele** [comment]
Perhaps if there is a pole at the origin, the lower limit of the omega vector should be below the indent_radius ?
