### ISSUE TITLE
using PID in interconnected system - improper transfer function error

### ISSUE THREAD

**Issue by rstoddard24** [python-control/python-control#654]
I have not been able to figure out how to use PID controller in a interconnected system; posting as an issue because it seems that this should be a very easy thing to do with python-control. If I am missing something obvious perhaps the documentation should be updated with an example. 

The issue is since a PID transfer function by itself is improper, I can't realize it in an InterconnmectedSystem (even tho the system transfer function is proper). The code below works if I change the controller transfer function to PI (since PI has proper transfer function by itself)

```
import control
# define process
A = np.array([[-10, -0.01], [1000, 1]])
B = np.array([[0], [1]])
C = np.array([[0, 1]])
D = np.array([[0]])
sys = control.ss(A, B, C, D) 
process = control.ss2io(sys, name='process', inputs='u', outputs='y')

# define controller
kp = 1
ki = 1
kd = 1
Cpid = kp + ki*control.tf([1], [1, 0]) + kd*control.tf([1, 0], [1])
controller = control.tf2io(Cpid,  name='control', inputs='u', outputs='y')

# define interconnected system
closed_loop_tf = control.InterconnectedSystem((process, controller), name='closed_loop',
                                               connections = [('control.u', '-process.y'), ('process.u', 'control.y')],
                                               inplist = ('control.u'), inputs = ('uref'),
                                               outlist = ('process.y', 'process.u'), outputs = ('y', 'u'))

# Simulate step response
ts = np.linspace(0, 20, num=201)
Uref = 5 * np.ones(ts.shape)
t, y = control.input_output_response(closed_loop_tf, ts, Uref, 0)
```

everything works to use above method to simulate interconnected system with PI controller, but with the above PID controller I get `ValueError: Transfer function is non-proper; can't convert to StateSpace system.`

please advise how to simulate interconnected system with PID controller

**Comment by sawyerbfuller** [comment]
Hi Ryan, a state-space system cannot represent an improper transfer function, and the internal representation of an LTI IOSystem is as a state-space system. The problem also arises if you try, e.g `control.tf2ss(Cpid)`. One common alternative is a "PIF", where the F refers to a low-pass filtered version of a derivative that has the form s/(as+1), where 1/a is the frequency of the high-frequency rolloff, so that the F term approximates a pure derivative up to the rolloff frequency. This is proper. Typically you would choose 1/a to be small relative to the frequencies of interest in your system.
