### ISSUE TITLE
keyword input always set True in forced_response causing error msgs

### ISSUE THREAD

**Issue by mvaccariunipi** [python-control/python-control#861]
Hi, 
I am writing because I find that in the newer versions of control (>= 0.9.0) when calling `lsim` the `transpose` keyword argument in `forced_response` is always set to `True` without checking the dimension of U entering the function.
This means that when passing inputs to `lsim` as described in ref:`time-series-convention` , i.e. U.shape=(m,N) and T.shape=(N,), the resulting error is always coming from `_check_convert_array`, that is, "Wrong shape (rows, columns): {a}. Expected: {e}.".

Is there a way to manage the inputs of `lsim` so to set `transpose=False` without entering the `timeresp.py` manually?

**Comment by murrayrm** [comment]
I looked into this and agree with the described behavior.  Since the intent of the MATLAB module is to provide compatibility with MATLAB, I don't think we need to add the `transpose` keyword.  If you are using the python-control convention, you should call `forced_response` (or `input_output_response`, for I/O systems) instead. Alternatively, you can just add `.T` to the input arrays passed to `lsim`.
